
image: node:16

pipelines:
  default:
      - step:
          name: Build
          caches:
            - node
          script:
            - npm install
            - npm run lint
            - npm build
