
image: node:16

pipelines:
  default:
      - step:
          name: Build
          caches:
            - node
          script:
            - yarn install
            - yarn lint
            - yarn build
